version: '3.7'
services:
    flask:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on:
            - redis
    redis:
        image: redis:5.0.7
        command: redis-server
